<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-GHFBK4A" ignored="0" name="Test" tests="2" failures="1" timestamp="28 Oct 2020 18:30:01 GMT" time="41.802" errors="0">
  <testcase name="loginTest" time="3.085" classname="com.ebanking.testcases.TC_loginTest_001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.ebanking.testcases.TC_loginTest_001.loginTest(TC_loginTest_001.java:67)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="addNewCustomer" time="17.883" classname="com.ebanking.testcases.TC_addCustomertest"/>
</testsuite> <!-- Test -->
